import {
  PLAYFIELD_COLUMNS,
	PLAYFIELD_ROWS,
	NEXT_FIELD_COLUMNS,
	NEXT_FIELD_ROWS,
  POINTS_FOR_LINES,
	CLASS_BTN,
	FIGURES,
} from './constants.js';
import { state } from './state.js';

export {
  PLAYFIELD_COLUMNS,
	PLAYFIELD_ROWS,
	NEXT_FIELD_COLUMNS,
	NEXT_FIELD_ROWS,
	POINTS_FOR_LINES,
  FIGURES,
	CLASS_BTN,
  state,
}
